function params = white_gui(params)
    % white_gui Brief description of GUI.

    %  Construct the components
    f = figure('Visible','on','Name','parameters',...
            'Position',[500, 500, 450, 285], 'Toolbar', 'none');

    ph = uipanel('Parent',f, 'Title', 'Experiment parameters',...
            'Position',[.05 .05 .9 .9]);

    uicontrol(ph,'Style','text',...
                'String','Subject ID',...
                'Units','normalized',...
                'Position',[.05 .85 .25 .10]);
            
    subject_ID = uicontrol(ph,'Style','edit',...
            'Units','normalized',...
            'String', params.subject,...
            'Position', [.05 .80 .25 .10]);
        
    uicontrol(ph,'Style','text',...
                'String','Annulus (bool)',...
                'Units','normalized',...
                'Position',[.05 .65 .25 .10]);  
            
    annulus = uicontrol(ph,'Style','edit',...
            'Units','normalized',...
            'String', num2str(params.annulus),...
            'Position', [.05 .6 .25 .10]);
        
    uicontrol(ph,'Style','text',...
                'String','constant stimulus (bool)',...
                'Units','normalized',...
                'Position',[.05 .45 .25 .10]);
            
    constant_stim = uicontrol(ph,'Style','edit',...
            'Units','normalized',...
            'String', num2str(params.constant_stim),...
            'Position', [.05 .4 .25 .10]);

    uicontrol(ph,'Style','text',...
                'String','Luminance (cd/m^2)',...
                'Units','normalized',...
                'Position',[.35 .85 .25 .10]);
            
    LUM = uicontrol(ph,'Style','edit',...
            'Units','normalized',...
            'String', num2str(params.LUM),...
            'Position', [.35 .8 .25 .10]);

    uicontrol(ph,'Style','text',...
                'String','rho (xyz distance)',...
                'Units','normalized',...
                'Position',[.35 .65 .25 .10]);
            
    RHO = uicontrol(ph,'Style','edit',...
            'Units','normalized',...
            'String', num2str(params.RHO),...
            'Position', [.35 .6 .25 .10]); 

    uicontrol(ph,'Style','text',...
                'String','# of colors',...
                'Units','normalized',...
                'Position',[.35 .45 .25 .10]);
            
    ncolors = uicontrol(ph,'Style','edit',...
            'Units','normalized',...
            'String', num2str(params.ncolors),...
            'Position', [.35 .4 .25 .10]); 

    uicontrol(ph,'Style','text',...
                'String','# of repeats',...
                'Units','normalized',...
                'Position',[.65 .85 .25 .10]);
            
    nrepeats = uicontrol(ph,'Style','edit',...
            'Units','normalized',...
            'String', num2str(params.nrepeats),...
            'Position', [.65 .8 .25 .10]); 
        
    uicontrol(ph,'Style','text',...
                'String','calibration file',...
                'Units','normalized',...
                'Position',[.65 .65 .25 .10]);    
            
    cal_file = uicontrol(ph,'Style','edit',...
            'Units','normalized',...
            'String', num2str(params.cal_file),...
            'Position', [.65 .6 .25 .10]); 

    uicontrol(ph,'Style','text',...
                'String','pause time (s)',...
                'Units','normalized',...
                'Position',[.65 .45 .25 .10]);
            
    pause_time = uicontrol(ph,'Style','edit',...
            'Units','normalized',...
            'String', num2str(params.pause_time),...
            'Position', [.65 .4 .25 .10]); 
    
    uicontrol(ph,'Style','pushbutton','String','start',...
            'Units','normalized',...
            'Position',[.38 .05 .25 .15], ...
            'Callback', 'uiresume(gcbf)');
        
    uiwait(f);
    
    %  Callbacks for white_gui
%     function get_params(~, ~, fig_handle)
%         
    params.subject = get(subject_ID,'String');
    params.annulus = str2double(get(annulus,'String'));
    params.constant_stim = str2double(get(constant_stim,'String'));
    params.LUM = str2double(get(LUM,'String'));
    params.RHO = str2double(get(RHO,'String'));
    params.ncolors = str2double(get(ncolors,'String'));
    params.nrepeats = str2double(get(nrepeats,'String'));
    params.cal_file = get(cal_file,'String');
    params.pause_time = str2double(get(pause_time,'String'));
    params.ntrials = params.ncolors * params.nrepeats;
    
    close all;
%     end

end