function params = white_gui(params)
    % white_gui Brief description of GUI.

    %  Construct the components
    f = figure('Visible','on','Name','parameters',...
            'Position',[500, 500, 450, 285], 'Toolbar', 'none');

    ph = uipanel('Parent',f, 'Title', 'Experiment parameters',...
            'Position',[.05 .05 .9 .9]);

    uicontrol(ph,'Style','text',...
                'String','Subject ID',...
                'Units','normalized',...
                'Position',[.05 .85 .25 .10]);
            
    subject_ID = uicontrol(ph,'Style','edit',...
            'Units','normalized',...
            'String', params.subject,...
            'Position', [.05 .80 .25 .10]);

    uicontrol(ph,'Style','text',...
                'String','# of colors',...
                'Units','normalized',...
                'Position', [.05 .65 .25 .10]);
            
    ncolors = uicontrol(ph,'Style','edit',...
            'Units','normalized',...
            'String', num2str(params.ncolors),...
            'Position', [.05 .6 .25 .10]); 

    uicontrol(ph,'Style','text',...
                'String','annulus',...
                'Units','normalized',...
                'Position',[.05 .48 .25 .07]);  
            
    annulus = uibuttongroup(ph, 'Units','Normalized', ...
        'Position', [.05 .23 .25 .25]);
    
    uicontrol('Style','Radio', 'Parent', annulus, ...
        'HandleVisibility','off', ...
        'Units','Normalized', ...
        'Position', [.15 .65 .6 .25], ...
        'String','off', 'Tag','0');
    
    uicontrol('Style','Radio', 'Parent', annulus, ...
        'HandleVisibility','off', ...
        'Units','Normalized', ...
        'Position',  [.15 .15 .6 .25], ...
        'String','on', 'Tag','1');
        
    uicontrol(ph,'Style','text',...
                'String','Luminance (cd/m^2)',...
                'Units','normalized',...
                'Position',[.35 .85 .25 .10]);
            
    LUM = uicontrol(ph,'Style','edit',...
            'Units','normalized',...
            'String', num2str(params.LUM),...
            'Position', [.35 .8 .25 .10]);

    uicontrol(ph,'Style','text',...
                'String','rho (xyz distance)',...
                'Units','normalized',...
                'Position',[.35 .65 .25 .10]);
            
    RHO = uicontrol(ph,'Style','edit',...
            'Units','normalized',...
            'String', num2str(params.RHO),...
            'Position', [.35 .6 .25 .10]); 

    uicontrol(ph,'Style','text',...
                'String','constant stim',...
                'Units','normalized',...
                'Position',[.35 .48 .25 .07]);
            
    constant_stim = uibuttongroup(ph, 'Units','Normalized', ...
        'Position', [.35 .23 .25 .25]);
    
    uicontrol('Style','Radio', 'Parent', constant_stim, ...
        'HandleVisibility','off', ...
        'Units','Normalized', ...
        'Position', [.15 .65 .6 .25], ...
        'String','true', 'Tag','1');
    
    uicontrol('Style','Radio', 'Parent', constant_stim, ...
        'HandleVisibility','off', ...
        'Units','Normalized', ...
        'Position',  [.15 .15 .6 .25], ...
        'String','false', 'Tag','0');
        
    uicontrol(ph,'Style','text',...
                'String','# of repeats',...
                'Units','normalized',...
                'Position',[.65 .85 .25 .10]);
            
    nrepeats = uicontrol(ph,'Style','edit',...
            'Units','normalized',...
            'String', num2str(params.nrepeats),...
            'Position', [.65 .8 .25 .10]); 
        
    uicontrol(ph,'Style','text',...
                'String','calibration file',...
                'Units','normalized',...
                'Position',[.65 .65 .25 .10]);    
            
    cal_file = uicontrol(ph,'Style','edit',...
            'Units','normalized',...
            'String', num2str(params.cal_file),...
            'Position', [.65 .6 .25 .10]); 

    uicontrol(ph,'Style','text',...
                'String','pause time (s)',...
                'Units','normalized',...
                'Position',[.65 .45 .25 .10]);
            
    pause_time = uicontrol(ph,'Style','edit',...
            'Units','normalized',...
            'String', num2str(params.pause_time),...
            'Position', [.65 .4 .25 .10]); 

    uicontrol(ph,'Style','text',...
                'String','screen',...
                'Units','normalized',...
                'Position',[.65 .3 .25 .10]);
            
    screen = uicontrol(ph,'Style','edit',...
            'Units','normalized',...
            'String', num2str(params.screen),...
            'Position', [.65 .25 .25 .10]); 
        
    uicontrol(ph,'Style','pushbutton','String','start',...
            'Units','normalized',...
            'Position',[.35 .02 .25 .15], ...
            'Callback', 'uiresume(gcbf)');
        
    uiwait(f);
          
    params.subject = get(subject_ID,'String');
    params.annulus = str2double(get(get(annulus,'SelectedObject'),'Tag'));
    params.constant_stim = str2double(get(get(annulus,'SelectedObject'),...
        'Tag'));
    params.LUM = str2double(get(LUM,'String'));
    params.RHO = str2double(get(RHO,'String'));
    params.ncolors = str2double(get(ncolors,'String'));
    params.nrepeats = str2double(get(nrepeats,'String'));
    params.cal_file = get(cal_file,'String');
    params.pause_time = str2double(get(pause_time,'String'));
    params.screen = str2double(get(screen,'String'));
    params.ntrials = params.ncolors * params.nrepeats;

    
    close all;

end